name: CountOnMe

on:
  push:
    branches:
      - main

jobs:
  configure:
      runs-on: ubuntu-latest

      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: AKIA2UC3FRBDIMFANS5U
            aws-secret-access-key: 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
            aws-region: ap-southeast-1
            
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2 

          
  build:
    runs-on: ubuntu-latest
    needs: configure
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image and push
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t 730335643718.dkr.ecr.ap-southeast-1.amazonaws.com/countonme-react --push ./CountOnMe-React
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Update ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: CountOnMe-React
        service: CountOnMe-React-service-3y5vcgqp
        cluster: CountOnMe
        wait-for-service-stability: true
        force-new-deployment: true
